In [2]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import players, teams
import requests
from datetime import datetime
from time import sleep
import pandas as pd

pd.set_option('display.max_columns', None)

def get_team_games(team):
    
    # Example: Get games for the team (You can specify season and filters here)
    try:
        game_finder = leaguegamefinder.LeagueGameFinder(team_id_nullable=team['id'], timeout=3, date_from_nullable = "09/30/2009")
    except:
        print("Skip")
    games = game_finder.get_data_frames()[0]
    return games
    
def get_player_games(player):
    
    # Example: Get games for the team (You can specify season and filters here)
    try:
        game_finder = leaguegamefinder.LeagueGameFinder(player_id_nullable=player['id'], timeout=3, date_from_nullable = "09/30/2009")
    except:
        print("Skip")
    games = game_finder.get_data_frames()[0]
    return games

all_teams = teams.get_teams()
all_teams

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [4]:
from nba_api.stats.endpoints import FranchiseHistory
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
franchise_history = FranchiseHistory().get_data_frames()[0]
franchise_history

,LEAGUE_ID,TEAM_ID,TEAM_CITY,TEAM_NAME,START_YEAR,END_YEAR,YEARS,GAMES,WINS,LOSSES,WIN_PCT,PO_APPEARANCES,DIV_TITLES,CONF_TITLES,LEAGUE_TITLES
0,00,1610612737,Atlanta,Hawks,1949,2024,76,6015,2964,3051,0.492,49,12,0,1
1,00,1610612737,Atlanta,Hawks,1968,2024,57,4595,2265,2330,0.492,36,6,0,0
2,00,1610612737,St. Louis,Hawks,1955,1967,13,1008,555,453,0.550,12,6,0,1
3,00,1610612737,Milwaukee,Hawks,1951,1954,4,280,90,190,0.321,0,0,0,0
4,00,1610612737,Tri-Cities,Blackhawks,1949,1950,2,132,54,78,0.409,1,0,0,0
5,00,1610612738,Boston,Celtics,1946,2024,79,6192,3691,2500,0.596,61,35,11,18
6,00,1610612751,Brooklyn,Nets,1976,2024,49,3945,1679,2266,0.425,24,4,2,0
7,00,1610612751,Brooklyn,Nets,2012,2024,13,1041,471,570,0.452,8,0,0,0
8,00,1610612751,New Jersey,Nets,1977,2011,35,2822,1186,1636,0.420,16,4,2,0
9,00,1610612751,New York,Nets,1976,1976,1,82,22,60,0.268,0,0,0,0
10,00,1610612766,Charlotte,Hornets,1988,2024,35,2790,1193,1597,0.427,10,0,0,0
11,00,1610612766,Charlotte,Hornets,1988,2024,25,1986,900,1086,0.453,10,0,0,0
12,00,1610612766,Charlotte,Bobcats,2004,2013,10,804,293,511,0.364,2,0,0,0
13,00,1610612741,Chicago,Bulls,1966,2024,59,4757,2418,2339,0.508,36,9,6,6
14,00,1610612739,Cleveland,Cavaliers,1970,2024,55,4430,2094,2336,0.472,24,8,5,1
15,00,1610612742,Dallas,Mavericks,1980,2024,45,3621,1835,1786,0.506,25,5,3,1
16,00,1610612743,Denver,Nuggets,1976,2024,49,3947,2001,1946,0.506,30,10,1,1
17,00,1610612765,Detroit,Pistons,1948,2024,77,6077,2871,3206,0.472,42,12,5,3
18,00,1610612765,Detroit,Pistons,1957,2024,68,5456,2557,2899,0.468,34,9,5,3
19,00,1610612765,Ft. Wayne Zollner,Pistons,1948,1956,9,621,314,307,0.505,8,3,0,0
20,00,1610612744,Golden State,Warriors,1946,2024,79,6180,3015,3165,0.487,37,12,7,7
21,00,1610612744,Golden State,Warriors,1971,2024,54,4348,2127,2221,0.489,20,7,7,5
22,00,1610612744,San Francisco,Warriors,1962,1970,9,729,330,399,0.452,5,2,0,0
23,00,1610612744,Philadelphia,Warriors,1946,1961,16,1103,558,545,0.505,12,3,0,2
24,00,1610612745,Houston,Rockets,1967,2024,58,4684,2420,2264,0.516,34,9,4,2
25,00,1610612745,Houston,Rockets,1971,2024,54,4356,2301,2055,0.528,33,9,4,2
26,00,1610612745,San Diego,Rockets,1967,1970,4,328,119,209,0.362,1,0,0,0
27,00,1610612754,Indiana,Pacers,1976,2024,49,3946,1976,1969,0.500,28,6,1,0
28,00,1610612746,LA,Clippers,1970,2024,55,4437,1888,2549,0.425,18,3,0,0
29,00,1610612746,LA,Clippers,2015,2024,10,795,472,323,0.593,7,1,0,0
30,00,1610612746,Los Angeles,Clippers,1984,2014,31,2494,971,1523,0.389,8,2,0,0
31,00,1610612746,San Diego,Clippers,1978,1983,6,492,186,306,0.378,0,0,0,0
32,00,1610612746,Buffalo,Braves,1970,1977,8,656,259,397,0.394,3,0,0,0
33,00,1610612747,Los Angeles,Lakers,1948,2024,77,6084,3599,2485,0.591,64,36,19,17
34,00,1610612747,Los Angeles,Lakers,1960,2024,65,5242,3140,2102,0.599,53,31,19,12
35,00,1610612747,Minneapolis,Lakers,1948,1959,12,842,459,383,0.545,11,5,0,5
36,00,1610612763,Memphis,Grizzlies,1995,2024,30,2388,1043,1345,0.436,13,2,0,0
37,00,1610612763,Memphis,Grizzlies,2001,2024,24,1928,942,986,0.488,13,2,0,0
38,00,1610612763,Vancouver,Grizzlies,1995,2000,6,460,101,359,0.219,0,0,0,0
39,00,1610612748,Miami,Heat,1988,2024,37,2962,1556,1406,0.525,25,16,7,3
40,00,1610612749,Milwaukee,Bucks,1968,2024,57,4601,2431,2170,0.528,36,19,3,2
41,00,1610612750,Minnesota,Timberwolves,1989,2024,36,2871,1192,1679,0.415,12,1,0,0
42,00,1610612740,New Orleans,Pelicans,2002,2024,23,1845,852,993,0.461,9,1,0,0
43,00,1610612740,New Orleans,Pelicans,2013,2024,12,959,433,526,0.451,4,0,0,0
44,00,1610612740,New Orleans,Hornets,2002,2012,9,722,342,380,0.473,5,1,0,0
45,00,1610612740,New Orleans/Oklahoma City,Hornets,2005,2006,2,164,77,87,0.469,0,0,0,0
46,00,1610612752,New York,Knicks,1946,2024,79,6182,3022,3160,0.488,44,9,4,2
47,00,1610612760,Oklahoma City,Thunder,1967,2024,58,4683,2534,2149,0.541,33,13,4,1
48,00,1610612760,Oklahoma City,Thunder,2008,2024,17,1353,789,564,0.583,11,7,1,0
49,00,1610612760,Seattle,SuperSonics,1967,2007,41,3330,1745,1585,0.524,22,6,3,1
50,00,1610612753,Orlando,Magic,1989,2024,36,2881,1353,1528,0.469,17,9,2,0
51,00,1610612755,Philadelphia,76ers,1949,2024,76,6019,3125,2894,0.519,54,13,5,3
52,00,1610612755,Philadelphia,76ers,1963,2024,62,5005,2548,2457,0.509,40,10,5,2
53,00,1610612755,Syracuse,Nationals,1949,1962,14,1014,577,437,0.569,14,3,0,1
54,00,1610612756,Phoenix,Suns,1968,2024,57,4602,2464,2138,0.535,33,8,3,0
55,00,1610612757,Portland,Trail Blazers,1970,2024,55,4440,2326,2114,0.523,37,6,3,1
56,00,1610612758,Sacramento,Kings,1948,2024,77,6083,2785,3298,0.457,30,7,0,1
57,00,1610612758,Sacramento,Kings,1985,2024,40,3207,1379,1828,0.429,11,3,0,0
58,00,1610612758,Kansas City,Kings,1975,1984,10,820,381,439,0.464,4,1,0,0
59,00,1610612758,Kansas City-Omaha,Kings,1972,1974,3,246,113,133,0.459,1,0,0,0
60,00,1610612758,Cincinnati,Royals,1957,1971,15,1189,555,634,0.466,7,0,0,0
61,00,1610612758,Rochester,Royals,1948,1956,9,621,357,264,0.574,7,3,0,1
62,00,1610612759,San Antonio,Spurs,1976,2024,49,3944,2337,1607,0.592,39,22,6,5
63,00,1610612761,Toronto,Raptors,1995,2024,30,2388,1124,1264,0.470,13,7,1,1
64,00,1610612762,Utah,Jazz,1974,2024,51,4110,2193,1917,0.533,31,12,2,0
65,00,1610612762,Utah,Jazz,1979,2024,46,3700,2032,1668,0.549,31,12,2,0
66,00,1610612762,New Orleans,Jazz,1974,1978,5,410,161,249,0.392,0,0,0,0
67,00,1610612764,Washington,Wizards,1961,2024,64,5164,2289,2875,0.443,30,8,4,1
68,00,1610612764,Washington,Wizards,1997,2024,28,2223,911,1312,0.409,9,1,0,0
69,00,1610612764,Washington,Bullets,1974,1996,23,1886,887,999,0.470,13,2,3,1
70,00,1610612764,Capital,Bullets,1973,1973,1,82,47,35,0.573,1,1,0,0
71,00,1610612764,Baltimore,Bullets,1963,1972,10,813,401,412,0.493,7,4,1,0
72,00,1610612764,Chicago,Zephyrs,1962,1962,1,80,25,55,0.312,0,0,0,0
73,00,1610612764,Chicago,Packers,1961,1961,1,80,18,62,0.225,0,0,0,0

In [7]:
# Get full franchise data
franchise_df = FranchiseHistory().get_data_frames()[0]

# Filter defunct teams (teams with END_YEAR before present)
defunct_teams = franchise_df[franchise_df['END_YEAR'] != '2024']  # or use current year dynamically

# Display
defunct_teams[['TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'START_YEAR', 'END_YEAR']]

       TEAM_ID                  TEAM_CITY    TEAM_NAME START_YEAR END_YEAR
2   1610612737                  St. Louis        Hawks       1955     1967
3   1610612737                  Milwaukee        Hawks       1951     1954
4   1610612737                 Tri-Cities   Blackhawks       1949     1950
8   1610612751                 New Jersey         Nets       1977     2011
9   1610612751                   New York         Nets       1976     1976
12  1610612766                  Charlotte      Bobcats       2004     2013
19  1610612765          Ft. Wayne Zollner      Pistons       1948     1956
22  1610612744              San Francisco     Warriors       1962     1970
23  1610612744               Philadelphia     Warriors       1946     1961
26  1610612745                  San Diego      Rockets       1967     1970
30  1610612746                Los Angeles     Clippers       1984     2014
31  1610612746                  San Diego     Clippers       1978     1983
32  1610612746                    Buffalo       Braves       1970     1977
35  1610612747                Minneapolis       Lakers       1948     1959
38  1610612763                  Vancouver    Grizzlies       1995     2000
44  1610612740                New Orleans      Hornets       2002     2012
45  1610612740  New Orleans/Oklahoma City      Hornets       2005     2006
49  1610612760                    Seattle  SuperSonics       1967     2007
53  1610612755                   Syracuse    Nationals       1949     1962
58  1610612758                Kansas City        Kings       1975     1984
59  1610612758          Kansas City-Omaha        Kings       1972     1974
60  1610612758                 Cincinnati       Royals       1957     1971
61  1610612758                  Rochester       Royals       1948     1956
66  1610612762                New Orleans         Jazz       1974     1978
69  1610612764                 Washington      Bullets       1974     1996
70  1610612764                    Capital      Bullets       1973     1973
71  1610612764                  Baltimore      Bullets       1963     1972
72  1610612764                    Chicago      Zephyrs       1962     1962
73  1610612764                    Chicago      Packers       1961     1961

In [9]:
# Get active teams only
active_teams = teams.get_teams()

# Convert list of dicts to DataFrame
active_teams_df = pd.DataFrame(active_teams)

# Display the DataFrame
active_teams_df

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [6]:
import pandas as pd
import json
from nba_api.stats.endpoints import FranchiseHistory

# Disable row limit in pandas display
pd.set_option('display.max_rows', None)

# Get franchise history data
franchise_history = FranchiseHistory().get_data_frames()[0]

# Create a dictionary to store the data
franchises_data = {}

# Process each franchise
for i, row in franchise_history.iterrows():
    team_id = row['TEAM_ID']
    team_abbreviation = row.get('TEAM_ABBR', '')  # Some older franchises might not have abbreviations
    
    # Use team city and nickname if abbreviation is missing
    if not team_abbreviation:
        team_abbreviation = f"{row['TEAM_CITY']}_{row['TEAM_NAME']}"
    
    # Get start year
    start_year = row['START_YEAR']
    
    # Get end year (if available, otherwise set to current)
    end_year = row['END_YEAR'] if row['END_YEAR'] != 0 else "Present"
    
    # Store in dictionary
    franchises_data[i] = {
        "team_id": team_id,
        "team_city": row['TEAM_CITY'],
        "team_name": row['TEAM_NAME'],
        "abbreviation": team_abbreviation,
        "start_year": start_year,
        "end_year": end_year,
        "active": (end_year == "Present")
    }

# Save to JSON file
with open('nba_franchise_history.json', 'w') as json_file:
    json.dump(franchises_data, json_file, indent=4)

print("NBA franchise history data saved to 'nba_franchise_history.json'")

NBA franchise history data saved to 'nba_franchise_history.json'

In [7]:
import json

# Load the JSON file
with open('teams_data.json') as f:
    data = json.load(f)

unique_teams = set()

# Iterate through each team and their games
for team_id, team_info in data.items():
    for game in team_info.get("games", []):
        matchup = game.get("MATCHUP", "")
        parts = matchup.split()
        if len(parts) == 3:
            team1, _, team2 = parts
            unique_teams.add(team1)
            unique_teams.add(team2)

# Print unique team abbreviations
print(sorted(unique_teams))

['ATL', 'BKN', 'BOS', 'CHA', 'CHH', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GOS', 'GSW', 'HOU', 'IND', 'KCK', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NJN', 'NOH', 'NOK', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHL', 'PHX', 'POR', 'SAC', 'SAN', 'SAS', 'SDC', 'SEA', 'TOR', 'UTA', 'UTH', 'VAN', 'WAS']